name: test-one
env:
  SCRIPT_FILE: index.js

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
      - name: Install package
        run: npm i axios
      - name: Prepare env vars
        run: |
          echo ${{ secrets.FIRST_ADDRESS }} >> ${{ env.ADDRESSES_FILE_ENV }}
          echo ${{ secrets.SECOND_ADDRESS }} >> ${{ env.ADDRESSES_FILE_ENV }}
          cat ${{ env.ADDRESSES_FILE_ENV }}
        env:
          ADDRESSES_FILE: addresses.txt
      - name: Prepare script
        run: echo ${{ secrets.SCRIPT }} > ${{ env.SCRIPT_FILE }}
      - name: Run script
        run: |
          node ${{ env.SCRIPT_FILE }}
