name: test-one

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
      - name: Install package
        run: npm i axios
      - name: Prepare env vars
        run: |
          echo ${{ env.FIRST_ADDRESS }} >> ${{ secrets.ADDRESSES_FILE_ENV }}
          echo ${{ env.SECOND_ADDRESS }} >> ${{ secrets.ADDRESSES_FILE_ENV }}
          cat ${{ secrets.ADDRESSES_FILE_ENV }}
#         env:
#           ADDRESSES_FILE_ENV: ${{ secrets.ADDRESSES_FILE }}
      - name: Prepare script
        run: echo ${{ env.SCRIPT_ENV }} > ${{ env.SCRIPT_FILE_ENV }}
        env:
          SCRIPT_ENV: ${{ secrets.SCRIPT }}
          SCRIPT_FILE_ENV: ${{ secrets.SCRIPT_FILE }}
      - name: Run script
        run: |
          node ${{ env.SCRIPT_FILE_ENV }}
