name: test-one
env:
  SCRIPT_FILE: index.js

on: workflow_dispatch

jobs:
  prepare_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
      - name: Install package
        run: npm ci
      - name: Prepare env vars
        run: |
          echo ${{ secrets.FIRST_ADDRESS }} >> ${{ env.ADDRESSES_FILE }}
          echo ${{ secrets.SECOND_ADDRESS }} >> ${{ env.ADDRESSES_FILE }}
        env:
          ADDRESSES_FILE: addresses.txt
      - name: Run script
        run: node ${{ env.SCRIPT_FILE }}
